mff_rams_plugin/config.py
mff_rams_plugin/templates/groupextra.html

Resubmission of https://github.com/MidwestFurryFandom/mff-rams-plugin/pull/2 for a cleaner PR.

Added extra dealer table properties

---

mff_rams_plugin/templates/static_views/stafferComps.html

Super simple, this is the content that was requested.  I have repurposed "Hours for refund" as the comped badge number.

Updated volunteer perk chart

---

mff_rams_plugin/templates/emails/dealers/application.html

Added a slice of logic to show/hide power price based on whether they asked for it.  Also updated some of the rest of the text.

Update dealer reg email

---

mff_rams_plugin/templates/common/index.html

The client OK-d.
Fixes https://github.com/MidwestFurryFandom/rams/issues/129

Updated index page per Rama's request

---

mff_rams_plugin/templates/emails/placeholders/dealer.txt
mff_rams_plugin/templates/emails/placeholders/guest.txt
mff_rams_plugin/templates/emails/placeholders/imported_volunteer.txt
mff_rams_plugin/templates/emails/placeholders/panelist.txt
mff_rams_plugin/templates/emails/placeholders/regular.txt
mff_rams_plugin/templates/emails/placeholders/reminder.txt
mff_rams_plugin/templates/emails/placeholders/volunteer.txt
mff_rams_plugin/templates/emails/reg_workflow/attendee_confirmation.html
mff_rams_plugin/templates/emails/reg_workflow/reg_notes.html

Added some template overrides and fixed a couple of errors in the reg_notes template.
Fixes https://github.com/MidwestFurryFandom/rams/issues/136

136email sending

---

mff_rams_plugin/templates/groups/index.html

Show a yes/no power column on the groups admin page.
A good overview tool for getting a feel for how many dealers want it.

Show power

---

mff_rams_plugin/configspec.ini
mff_rams_plugin/templates/emails/dealers/approved.html
mff_rams_plugin/templates/emails/dealers/payment_confirmation.html
mff_rams_plugin/templates/emails/reg_workflow/group_confirmation.html
mff_rams_plugin/templates/static_views/dealerRules.html

Fixes https://github.com/MidwestFurryFandom/rams/issues/141 https://github.com/MidwestFurryFandom/rams/issues/142 https://github.com/MidwestFurryFandom/rams/issues/147 https://github.com/MidwestFurryFandom/rams/issues/149

141 142 dealear accept emails

---

mff_rams_plugin/models.py

Prevents https://github.com/MidwestFurryFandom/rams/issues/202 from happening in the future.

Don't mark staff for preprint before the event

---

mff_rams_plugin/models.py
mff_rams_plugin/templates/kiosk_printing/print_badges.html
mff_rams_plugin/templates/preregistration/disclaimers.html
mff_rams_plugin/templates/regextra.html

Apply fixes for at-door registration and customize badge printing for MFF's needs

Merge Staging

---

alembic/versions/1da162016924_add_tax_field_for_dealers.py
mff_rams_plugin/automated_emails.py
mff_rams_plugin/model_checks.py
mff_rams_plugin/models.py
mff_rams_plugin/templates/emails/dealers/application.html
mff_rams_plugin/templates/emails/dealers/approved.html
mff_rams_plugin/templates/emails/dealers/payment_confirmation.html
mff_rams_plugin/templates/emails/dealers/payment_reminder.txt
mff_rams_plugin/templates/emails/reg_workflow/group_confirmation.html
mff_rams_plugin/templates/groupextra.html
mff_rams_plugin/templates/groups/index.html
mff_rams_plugin/templates/groups/waitlist.html
mff_rams_plugin/templates/preregistration/attendee_donation_form.html

Adds the IBT number field, allows dealers to edit some of their information after approval, makes payment due dates based on approval time, and fixes some cosmetic issues.

Update dealer applications for 2018 pre-reg

---

mff_rams_plugin/models.py

MAGFest renamed this property, so now we have to as well! Fixes https://github.com/MidwestFurryFandom/mff-rams-plugin/issues/38.

Override new paid_for_a_shirt property

---

mff_rams_plugin/model_checks.py
mff_rams_plugin/templates/regextra.html

Fixes https://github.com/MidwestFurryFandom/mff-rams-plugin/issues/45.

Allow for both promo code and agent code use

---

mff_rams_plugin/templates/static_views/dealer_reg_closed.html
mff_rams_plugin/templates/static_views/dealer_reg_not_open.html

Cosmetic change, see discussion in https://github.com/MidwestFurryFandom/art_show/issues/68

Override dealer closed templates to not mention the date

---

mff_rams_plugin/templates/groupextra.html

Fix power price reg

---

mff_rams_plugin/templates/emails/reg_workflow/attendee_confirmation.html
mff_rams_plugin/templates/emails/reg_workflow/reg_notes.html
mff_rams_plugin/templates/preregistration/disclaimers.html

Reverts MidwestFurryFandom/mff-rams-plugin#49
Before merging, we need to change the dates referenced in the text to not be 2017.

Revert "Altered refs to refundable badges to be nonrefundable"

---

mff_rams_plugin/automated_emails.py
mff_rams_plugin/templates/emails/dealers/pending_waitlisted.txt
mff_rams_plugin/templates/emails/dealers/waitlist_closing.txt

We recently discovered that the behavior of emails associated w/ the dealer waitlist was incorrect. This fixes it well enough for now, and lays in the groundwork for fixing more later if needed.

Update waitlist email

---

mff_rams_plugin/templates/emails/dealers/approved.html

Fixed leftover ref to config value instead of group

---

mff_rams_plugin/templates/emails/dealers/approved.html

It's less bad than it is brittle and inelegant. It is, however, fast.

Fix 86 badly

---

mff_rams_plugin/templates/emails/art_show/application.html

Fixes https://github.com/MidwestFurryFandom/art_show/issues/67.

Customize wording for art show application confirmation

---

mff_rams_plugin/models.py
mff_rams_plugin/templates/art_show_applications/edit.html

Depends on https://github.com/MidwestFurryFandom/art_show/pull/91. Fixes https://github.com/MidwestFurryFandom/art_show/issues/89.

Override app edit template to remove mailing address

---

mff_rams_plugin/templates/baseextra.html

Fixes https://github.com/MidwestFurryFandom/mff-rams-plugin/issues/75.

Re-enable delete button on '/groups/form'

---

mff_rams_plugin/templates/groupextra.html

Fixes https://github.com/MidwestFurryFandom/mff-rams-plugin/issues/52. Fixes https://github.com/MidwestFurryFandom/mff-rams-plugin/issues/53.

Make more fields editable after dealer has been approved

---

mff_rams_plugin/models.py

Fixes https://github.com/MidwestFurryFandom/mff-rams-plugin/issues/97

Account for 0 tables in tables_repr

---

mff_rams_plugin/site_sections/mff_reports.py

Brendan looked at this on Staging and approved the content and order.

Added a dealer publication listing report

---

mff_rams_plugin/config.py
mff_rams_plugin/site_sections/mff_reports.py
mff_rams_plugin/templates/mff_reports/attendance_graph.html

Fixes https://github.com/MidwestFurryFandom/mff-rams-plugin/issues/67 by adding a new report that includes anyone whose badge is a Complete status (i.e., they can check in), plus badges in paid or comped groups.

Add MFF daily attendance report

---

mff_rams_plugin/templates/preregistration/check_if_preregistered.html

Updated prereg check language

---

mff_rams_plugin/site_sections/mff_reports.py

I am _fairly sure_ Brendan wanted this and not the "All Dealers Detailed Report" that I had, so I modified that into being the "Full Dealers Report" requested in #102.
fixes #102 
fixes #92

Switched all-detailed for full as specced

---

mff_rams_plugin/site_sections/mff_reports.py

Adds the reports for Dealers Application Review and the Illinois Department of Revenue.
fixes #101 & #104 
Approved by Brendan.

Add IDOR and Dealer Applications reports

---

mff_rams_plugin/model_checks.py

Fixes https://github.com/MidwestFurryFandom/rams/issues/235.
This will need an extra couple lines if we also want the IBT number to be required instead of optional.

Add validation for IBT Number

---

mff_rams_plugin/models.py

Depends on https://github.com/MidwestFurryFandom/rams/pull/271 to make a difference. Fixes https://github.com/MidwestFurryFandom/rams/pull/271. We'll want to resave groups after merging this PR.

Automatically mark dealers with Guest badges as approved

---

mff_rams_plugin/config.py
mff_rams_plugin/templates/kiosk_printing/print_badges.html

Menu and reload script changes for MFF specific pages for the dual print queue system.

Dual print queues

---

mff_rams_plugin/templates/emails/reg_workflow/attendee_confirmation.html

Implemented wording changes for dealer assistant

---

mff_rams_plugin/config.py

Fixes https://github.com/MidwestFurryFandom/rams/issues/279

Move MFF badge stock checks to mff-rams-plugin

---

mff_rams_plugin/site_sections/mff_reports.py

It could maybe be formatted nicer, but it does work.

Added phone number to report

---

mff_rams_plugin/models.py

Fixes https://github.com/MidwestFurryFandom/rams/issues/219

Applies age discount to presold one day badges

---

mff_rams_plugin/models.py

Reprint badges for attendees who change their name on check-in

---

mff_rams_plugin/automated_emails.py
mff_rams_plugin/models.py
mff_rams_plugin/templates/static_views/slow_load.html

Found a few MFF-specific bits while reviewing the big merge into MAGFest (https://github.com/magfest/ubersystem/pull/3461), so I'm moving them here.
As this is part of the merge _from_ MFF _to_ MAGFest, this is being billed to MAGFest.

Move miscellaneous overrides to MFF Plugin

---

mff_rams_plugin/models.py

Using the event plugin to override a hybrid property doesn't actually work (and it's not clear it ever did), so we're moving this into the main plugin. It should be safe to change it.

Move changes to is_dealer expression back to main plugin

---

mff_rams_plugin/models.py

(angry gargling)
English translation: somehow while juggling feature branches I almost entirely undid all the changes from https://github.com/MidwestFurryFandom/mff-rams-plugin/pull/150. This re-does them.

Remove is_dealer property. Again.

---

mff_rams_plugin/templates/emails/dealers/approved.html
mff_rams_plugin/templates/emails/placeholders/dealer.txt

Per Brendan's request, and one minor copyedit of my own.

Made minor updates for 2019

---

mff_rams_plugin/templates/regextra.html

This change didn't get moved when we merged all MFF code into MAGFest, but it should have. It fixed https://github.com/MidwestFurryFandom/rams/issues/189. We'll need this when we merge https://github.com/MidwestFurryFandom/rams/pull/334.

Move fix for rams#189 to the MFF plugin

---

mff_rams_plugin/model_checks.py
mff_rams_plugin/models.py

Fixes https://github.com/MidwestFurryFandom/rams/issues/345.

Check cellphone, and stop requiring comped reason for staff

---

mff_rams_plugin/models.py

Fixes https://github.com/MidwestFurryFandom/rams/issues/342.

Account for staff ribbon in staffing adjustments

---

mff_rams_plugin/templates/regextra.html

We don't want them to uncheck this box, and the wording causes confusion. Fixes https://github.com/MidwestFurryFandom/rams/issues/344.

Hide staffing checkbox for staff

---

alembic/versions/6fd3a80ca4e0_initial_migration.py
alembic/versions/f08f4606351c_add_tax_number_column_for_marketplace_.py
mff_rams_plugin/models.py
mff_rams_plugin/templates/preregistration/attendee_donation_form.html

Part of https://github.com/MidwestFurryFandom/rams/issues/307.

Add Tax Number to Marketplace apps

---

mff_rams_plugin/models.py
mff_rams_plugin/templates/art_show_applications/edit.html

For some reason we didn't merge the original fix into mff-staging, only master.

Remove mailing address, again

---

mff_rams_plugin/site_sections/mff_reports.py
mff_rams_plugin/templates/art_show_applications/edit.html
mff_rams_plugin/templates/emails/dealers/application.html
mff_rams_plugin/templates/emails/dealers/approved.html
mff_rams_plugin/templates/emails/dealers/payment_confirmation.html
mff_rams_plugin/templates/emails/dealers/payment_reminder.txt
mff_rams_plugin/templates/emails/placeholders/regular.txt
mff_rams_plugin/templates/emails/reg_workflow/attendee_confirmation.html
mff_rams_plugin/templates/emails/reg_workflow/group_confirmation.html
mff_rams_plugin/templates/groupextra.html
mff_rams_plugin/templates/groups/index.html
mff_rams_plugin/templates/groups/waitlist.html
mff_rams_plugin/templates/preregistration/attendee_donation_form.html
mff_rams_plugin/templates/preregistration/paid_preregistrations.html

Also fixes some display errors with cents being displayed as dollars. Depends on https://github.com/MidwestFurryFandom/rams/pull/383.

Unify currency formatting

---

mff_rams_plugin/templates/preregistration/attendee_donation_form.html

Reflects an update in the core repo where we call Charge on an attendee rather than a charge object -- before this fix, the entire server would 504.

Fix upgrade payment crash

---

mff_rams_plugin/models.py
mff_rams_plugin/templates/art_show_applications/edit.html

Also integrates the changes from https://github.com/MidwestFurryFandom/rams/pull/382/commits/f08cae12f4626790a5675a581017d0d1045b0d21.

Improve handling of art show apps without attendees

---

mff_rams_plugin/templates/emails/dealers/application.html
mff_rams_plugin/templates/emails/reg_workflow/attendee_confirmation.html
mff_rams_plugin/templates/emails/reg_workflow/reg_notes.html
mff_rams_plugin/templates/preregistration/paid_preregistrations.html

Fixes https://github.com/MidwestFurryFandom/rams/issues/395. Fixes https://github.com/MidwestFurryFandom/rams/issues/394. https://github.com/MidwestFurryFandom/rams/issues/397.

Update MFF confirmation emails

---

mff_rams_plugin/templates/emails/reg_workflow/refund_policy.html
mff_rams_plugin/templates/emails/reg_workflow/under_18_reminder.txt
mff_rams_plugin/templates/preregistration/paid_preregistrations.html

A few small text changes and email overrides before prereg launch tomorrow.

Last minute fixes

---

mff_rams_plugin/models.py

Companion to https://github.com/MidwestFurryFandom/rams/pull/476.

Remove art show incomplete_reason

---

mff_rams_plugin/model_checks.py

Fixes https://github.com/MidwestFurryFandom/rams/issues/482.

Don't enforce badge ranges for staff

---

mff_rams_plugin/config.py
mff_rams_plugin/models.py

Removes references to old properties from the kiosk printing code

Clean up kiosk print code

---

mff_rams_plugin/site_sections/mff_reports.py
mff_rams_plugin/templates/landing/index.html

Corresponds to https://github.com/MidwestFurryFandom/rams/pull/511/commits/9df8e8a421782f2301bce9ec61bdea85047a737f and copies the changes to this overridden template.

Updating landing page for kiosk mode

---

mff_rams_plugin/models.py

Overrides the merch_items property so that we can use the merch admin page to hand out Sponsor and Shiny Sponsor merch

Add merch to Sponsors and Shiny Sponsors

---

alembic/versions/8d17ab462e66_add_review_notes_field_for_dealers.py
mff_rams_plugin/config.py
mff_rams_plugin/configspec.ini
mff_rams_plugin/models.py
mff_rams_plugin/site_sections/mff_reports.py
mff_rams_plugin/templates/baseextra.html
mff_rams_plugin/templates/groupextra.html

Several updates to the dealer application form, including extra power options

Update dealer application form

---

mff_rams_plugin/config.py
mff_rams_plugin/configspec.ini
requirements.txt

Allows MFF to manage 'secret' config via AWS.

Add key fetching from AWS

---

mff_rams_plugin/templates/groupextra.html
mff_rams_plugin/templates/regextra.html

Fixes the behavior of the Power Level field, which would reset if you got a serverside validation error. Also updates the Registration Code help text to refer to logging in.

Minor prereg form fixes

---

mff_rams_plugin/config.py
mff_rams_plugin/model_checks.py
mff_rams_plugin/models.py
mff_rams_plugin/templates/emails/dealers/application.html
mff_rams_plugin/templates/emails/dealers/approved.html
mff_rams_plugin/templates/groupextra.html

Admins are now able to set a power fee, and they're required to do so for tier 4 power. Also includes a smattering of minor fixes for issues found while testing.

Add ability to set custom power fee

---

mff_rams_plugin/models.py

Requires https://github.com/MidwestFurryFandom/rams/pull/561.

Add extra import fields

---

mff_rams_plugin/models.py
mff_rams_plugin/templates/emails/dealers/approved.html
mff_rams_plugin/templates/groupextra.html

We weren't actually adding the power cost to the dealer's group price if they had tier 4 power. This fixes that.

Fix power cost calculation

---

alembic/versions/9abc513c99cb_add_list_of_accessibility_request_.py
mff_rams_plugin/configspec.ini
mff_rams_plugin/models.py
mff_rams_plugin/site_sections/mff_reports.py
mff_rams_plugin/templates/mff_reports/comped_badges.html
mff_rams_plugin/templates/regextra.html

Allows attendees to accept from a list of accommodations during prereg

Add accessibility options

---

mff_rams_plugin/templates/regextra.html

Part of fixing https://github.com/MidwestFurryFandom/rams/issues/570.

Add fursuiting to list of possible reasons to contact someone

---

mff_rams_plugin/templates/emails/dealers/application.html

The dealer confirmation emails had some formatting issues. Also updates the text to give dealers room heads more time to review applications.

Update dealer confirmation emails

---

mff_rams_plugin/config.py

Should hopefully fix the performance issues we had earlier with sponsor and shiny sponsor badge stocks.

Cache sponsor/shiny badge counts

---

mff_rams_plugin/models.py

Part of https://github.com/MidwestFurryFandom/rams/pull/591. Also fixes a display issue where staff confirmation pages would say "Staff / Staff"

Add MFF-specific 'undo extras'

---

mff_rams_plugin/templates/emails/dealers/pending_waitlisted.txt

Requested by Wylde: https://jira.furfest.org/browse/SEI_SD-589

Added requested lottery ticket section to waitlist email

---

mff_rams_plugin/models.py

We no longer need this override and it will cause problems if we leave it in.

Remove calculate_badge_cost override

---

mff_rams_plugin/receipt_items.py

This assumes that the power fee should be added to the group's total -- if not, we need to change this.

Account for group overridden cost in plugin

---

mff_rams_plugin/model_checks.py

I don't know how they're doing it but they're not going to do it after this.

Stop people buying badges that don't exist

---

mff_rams_plugin/automated_emails.py
mff_rams_plugin/configspec.ini
mff_rams_plugin/templates/emails/art_show/charity.txt

Add charity email for art show

---

mff_rams_plugin/model_checks.py

"Oh, it's fine, just deploy this," I said. "This shouldn't cause any problems," I said.

Stop preventing existing shiny sponsors from saving their badges

---

mff_rams_plugin/automated_emails.py

Fix volunteer email

---

mff_rams_plugin/templates/emails/volunteer_interest.html

Literally how did I not catch this

Fix volunteer email text

---

mff_rams_plugin/automated_emails.py
mff_rams_plugin/model_checks.py
mff_rams_plugin/models.py
mff_rams_plugin/receipt_items.py
mff_rams_plugin/templates/emails/placeholders/reminder.txt
mff_rams_plugin/templates/emails/volunteer_interest.html
mff_rams_plugin/templates/groupextra.html
mff_rams_plugin/templates/regextra.html

Includes MFF-specific changes to go with https://github.com/MidwestFurryFandom/rams/pull/632. Also fixes the sold out checks for sponsors and shiny sponsor badges.

Add bug fixes required at-event

---

mff_rams_plugin/site_sections/mff_reports.py
mff_rams_plugin/templates/mff_reports/dealer_cost_summary.html

Adds a CSV report of all dealer membership in valid dealer groups, and a dealer cost breakdown page.

Add dealer reports

---

alembic/versions/e86fcf34f217_make_fursuiting_a_checkbox.py
mff_rams_plugin/__init__.py
mff_rams_plugin/config.py
mff_rams_plugin/configspec.ini
mff_rams_plugin/forms.py
mff_rams_plugin/model_checks.py
mff_rams_plugin/models.py
mff_rams_plugin/templates/forms/badge_extras.html
mff_rams_plugin/templates/forms/consents.html
mff_rams_plugin/templates/forms/other_info.html
mff_rams_plugin/templates/forms/personal_info.html
mff_rams_plugin/templates/regextra.html

Converts the MFF-specific extra fields for prereg to the new UX/form system. Depends on https://github.com/MidwestFurryFandom/rams/pull/647.

Update MFF prereg forms

---

mff_rams_plugin/config.py
mff_rams_plugin/templates/attendee_card_extra.html
mff_rams_plugin/templates/forms/badge_extras.html
mff_rams_plugin/templates/forms/other_info.html
mff_rams_plugin/templates/forms/personal_info.html

Fixes MFF-specific fields on mobile, and also adds a price to the Attendee badge on the prereg page. I will probably have to do something special for the confirmation page assuming we DON'T want the price displayed there (do we?)

Prereg fixes round 1

---

mff_rams_plugin/forms.py
mff_rams_plugin/validations/attendee.py
mff_rams_plugin/validations/group.py

Mirrors https://github.com/MidwestFurryFandom/rams/pull/656 to fix bugs that prevent any registrations from working.

Fix blocking bugs for reg testing

---

mff_rams_plugin/forms.py
mff_rams_plugin/templates/groups/index.html
mff_rams_plugin/templates/mff_reports/comped_badges.html
mff_rams_plugin/templates/mff_reports/dealer_cost_summary.html
mff_rams_plugin/templates/preregistration/banned.html
mff_rams_plugin/templates/preregistration/check_if_preregistered.html

Resetting to mff-staging from the art show launch feature branch.

Merge changes from art show launch

---

mff_rams_plugin/forms.py
mff_rams_plugin/models.py
mff_rams_plugin/templates/forms/attendee/prereg_other_info.html

Fixes SEI_SD-1726 by adding the table name to the last page of dealer prereg with a callout if the table name is the same as their full name.

Add table name check

---

alembic/versions/57e9f219b8db_add_dealer_fields_for_2025.py
mff_rams_plugin/configspec.ini
mff_rams_plugin/forms.py
mff_rams_plugin/models.py
mff_rams_plugin/site_sections/mff_reports.py
mff_rams_plugin/templates/emails/reg_workflow/attendee_confirmation.html
mff_rams_plugin/templates/emails/reg_workflow/group_confirmation.html
mff_rams_plugin/templates/forms/group/admin_table_info.html
mff_rams_plugin/templates/forms/group/table_info.html

Fixes https://jira.furfest.org/browse/SEI_SD-1926 by adding a ton of new fields for dealers during prereg, after acceptance, and on the admin page. Relies on file upload support in the main plugin.

Add dealer fields for 2025

---

.github/workflows/ci-docker.yaml
Dockerfile

Build arm64 compatible containers as well as amd64

Include multi platform build

---

mff_rams_plugin/configspec.ini
mff_rams_plugin/models.py

We were uploading to the mff_rams_plugin plugin, which we... do not want. Also adds a line to suppress errors about empty files.

Fix table photo uploads

---

mff_rams_plugin/models.py
mff_rams_plugin/templates/forms/attendee/personal_info.html
mff_rams_plugin/templates/forms/hotel/room_lottery.html
mff_rams_plugin/templates/forms/hotel/suite_lottery.html
mff_rams_plugin/templates/hotel_lottery/lottery_tos.html

Also updates an email address shown to staff badges.

Update hotel lottery text for staff lottery 2025

---

mff_rams_plugin/templates/emails/dealers/declined.txt
mff_rams_plugin/templates/emails/dealers/pending_waitlisted.txt

Update info for waitlisted/declined dealer email
