mff_rams_plugin/templates/preregistration/paid_preregistrations.html

Addresses one of the complaints about the "long session cookie" or whatever.  Kills off the list of prior regs from the computer, which should prevent attendees from accessing someone else's reg if they use the same machine (let's assume most likely scenario is mischievous roommates).
Fixes https://github.com/MidwestFurryFandom/rams/issues/128

Removed previous registrations from this computer section

---

mff_rams_plugin/templates/regextra.html

No length check, but it works on my dev box.
Fixes https://github.com/MidwestFurryFandom/rams/issues/126

Updated badge name length text to 30 chars

---

mff_rams_plugin/models.py

Fixes the sponsor-attendee's preference not setting their shirt properly.

Overloaded shirt fn to record choice at reg

---

mff_rams_plugin/templates/preregistration/attendee_donation_form.html

Jinja2 (for some reason) doesn't count None as falsey in certain cases, so prints out "None" when an attendee doesn't have an overridden price. We've updated the badge_cost property to accommodate 'overridden price' anyway, so we just have to fix the page display.
Fixes https://github.com/MidwestFurryFandom/art_show/issues/16.

Display badge price correctly

---

mff_rams_plugin/models.py
mff_rams_plugin/templates/regextra.html

Removes a duplicate function, and forces the `omit_badge` checkbox to be checked if it is present.

Update from mff-staging

---

mff_rams_plugin/templates/regextra.html

There were reports of volunteers accidentally setting print_pending back to True after a badge was printed. It's not super clear why this is happening, but one possible cause is that a page is loaded while print_pending is true, the badge gets sent to the printer, and then the checkbox is updating the attendee when a page is saved. This removes the checkbox so that no longer can happen.

Make 'print pending' text instead of a checkbox

---

mff_rams_plugin/model_checks.py
mff_rams_plugin/templates/baseextra.html
mff_rams_plugin/templates/regextra.html

The art show plugin (theoretically) allows both promo code use and agent code use, but MFF only needs the latter, so we want to change some cosmetic things to reflect that.

Configure MFF to replace promo codes with agent codes

---

mff_rams_plugin/templates/preregistration/disclaimers.html

Disclaimer has two links to websites and we want those to come up in a new window attendees don't screw up their reg.

Added targets to disclaimer links

---

mff_rams_plugin/templates/emails/reg_workflow/attendee_confirmation.html
mff_rams_plugin/templates/preregistration/disclaimers.html

Badges are no longer refundable, and now our pages reflect that.

Altered refs to refundable badges to be nonrefundable

---

mff_rams_plugin/templates/groupextra.html

The form's HTML was all wrong, so no data was making it to the model. Whoops. Fixes https://github.com/MidwestFurryFandom/rams/issues/234

Actually save and load IBT number

---

mff_rams_plugin/templates/emails/reg_workflow/attendee_confirmation.html

Blithe had some input on cleaning up the wording (nixing passive voice) and we've cleaned it up a bit as a result. Just hits the email. The disclaimers page was already consistent with this.

Update refund wording

---

mff_rams_plugin/automated_emails.py
mff_rams_plugin/configspec.ini
mff_rams_plugin/models.py

Adds `dealer_payments_days` to this plugin's config file, so we can change how long dealers have to pay if we need to.

Make dealer's due date configurable

---

mff_rams_plugin/site_sections/mff_reports.py

Adds a bunch of options in a new report on the mff-rams-plugin section of the sitemap. It's more an object export than a table export, but I think that does what we want. Alternately we could tweak the report that's down in summary. I'm not sure what the most-right answer is.
fixes #33

Added an export that includes categories

---

mff_rams_plugin/model_checks.py

Fixes https://github.com/MidwestFurryFandom/mff-rams-plugin/issues/65 (part 1). We also need https://github.com/MidwestFurryFandom/rams/pull/257, since the model checks fall back to the core plugin in this case.

Stop model-checking admin changes to dealers

---

mff_rams_plugin/templates/baseextra.html

Fixes https://github.com/MidwestFurryFandom/rams/issues/231. We had been trying to prevent attendees from entering emoji into fields, but it turns out that this stopped working at some point. We still have serverside validation, so while it's a little less user-friendly, we'll just use that.

Remove broken clientside anti-emoji validation

---

mff_rams_plugin/templates/kiosk_printing/print_badges.html

This will need to be tested with a printer, since I had to change the `display` property to get it to work. Fixes https://github.com/MidwestFurryFandom/rams/issues/207 by forcing a line break for very long badge name.

Add break-word wrapping to badge printing page

---

mff_rams_plugin/models.py

For some reason this was only present in master, causing staging to work as expected and master to... not.
Fixes https://github.com/MidwestFurryFandom/art_show/issues/229.

Unremove Art Show incomplete_reason override

---

mff_rams_plugin/models.py
mff_rams_plugin/templates/groupextra.html

When MAX_DEALERS is set to 0, we default to letting dealers buy badges equal to the number of tables they buy + 1. MFF wants a different number (3 per table, up to 12), so this overrides the appropriate properties and JS.
This also depends on https://github.com/MidwestFurryFandom/rams/pull/299.

Override default number of max dealer badges

---

alembic/versions/0f7426266803_add_fursuiting_column.py
mff_rams_plugin/configspec.ini
mff_rams_plugin/model_checks.py
mff_rams_plugin/models.py
mff_rams_plugin/templates/regextra.html

Adds a set of radio buttons to see if attendees are planning on fursuiting.
The buttons currently look like this:
Neither "No" or "Yes" is selected in that screenshot. Unfortunately, having only two options makes it ambiguous and people may not realize that. We may want to instead have "No/Yes/Not Sure" just to make the UI a little more clear. We can also change the colors of the buttons.
We will also probably want more formal wording for the explanation.

Add fursuiting check to prereg

---

mff_rams_plugin/templates/regextra.html

We use col-sm-3 everywhere else, so we're porting that here and removing help text for the admin page.

Fix form field offsets and help text

---

mff_rams_plugin/models.py
mff_rams_plugin/templates/regextra.html

The new function meant to override the behavior of our presave adjustments wasn't being run because it started with an underscore. This commit also unhides the staffing checkbox on the admin form for easier use.

Actually fix behavior of Staff and Volunteer ribbons

---

mff_rams_plugin/templates/art_show_applications/edit.html

There were differences between this template and the current template in art_show, and this version had a few bugs in the logic. I've replaced it with the template in art_show and re-removed the mailing address form (which is why we're overriding this template in the first place).

Fix attendee-facing art show app page

---

.gitignore
alembic/versions/f08f4606351c_add_tax_number_column_for_marketplace_.py
mff_rams_plugin/models.py

Fixes https://jira.furfest.org/browse/SEI_SD-121 -- the incomplete_reason for the art show app had different conditions than the template that relied on it, causing them to disagree on whether the attendee needed to pay or not.

Make incomplete_reason agree with template

---

mff_rams_plugin/models.py

This was a regression bug that was preventing artists from paying, and making piece counts not show up in the admin list of applications.

Count 'paid' apps as complete

---

mff_rams_plugin/config.py

This property is complex and checks the database multiple times for badge availability, and was being called multiple times in a pageload. We now cache the property per pageload, reducing the load time of /registration/register from ~11 seconds to ~2.

Cache AT_THE_DOOR_BADGE_OPTS to improve performance

---

.gitignore
mff_rams_plugin/config.py
mff_rams_plugin/site_sections/mff_reports.py
mff_rams_plugin/templates/baseextra.html
setup.py

Changes URLs to match the new integrated badge_printing plugin and removes references to outdated permissions settings.

Update MFF plugin for the latest version of RAMS

---

mff_rams_plugin/templates/art_show_applications/edit.html

We override the art show application page, so we need to reflect updates from https://github.com/MidwestFurryFandom/rams/pull/392 here as well.

Update art show app page for accounts

---

mff_rams_plugin/config.py
mff_rams_plugin/templates/groupextra.html

Fixes https://github.com/MidwestFurryFandom/rams/issues/406
Adds the 12x12 suite option (new) and also removes the table_prices div which uses a function that seems to just sum table prices, which is all wrong, and which duplicates the prices in the dropdown.

Fix dealer prices

---

mff_rams_plugin/templates/emails/reg_workflow/attendee_confirmation.html

Attendees are reporting that their confirmation email does not have a space between the last character of the reg code and the word 'and' that follows it. This is supported by a screenshot. This is intended to resolve that.

Added space to keep the and from the end of the reg code

---

mff_rams_plugin/templates/baseextra.html
mff_rams_plugin/templates/regextra.html

Once we merge https://github.com/MidwestFurryFandom/rams/pull/475, the reprint fee field will be shown properly along with everything else, so we don't need to force it to display in this plugin anymore.

Remove duplicate print fields

---

mff_rams_plugin/model_checks.py
mff_rams_plugin/templates/groupextra.html

Fixes https://github.com/MidwestFurryFandom/rams/issues/465. This is trickier than it looks, as we can't override the page handler that processes this form and it assumes that all fields are editable.

Let approved dealers update their tax ID

---

mff_rams_plugin/model_checks.py

A logic error prevented anyone with a staff badge from being comped without a reason filled in. Whoops.

Allow Staff badges to be comped

---

mff_rams_plugin/config.py

MFF opens at-door sales on Thursday, but doesn't actually sell Thursday badges. This change ensures we won't actually try to sell people Thursday badges.

Only sell Friday, Saturday, and Sunday badges

---

mff_rams_plugin/templates/groupextra.html

Who knew it was so difficult to manage the starting state of a dropdown for an integer field that also needs a null state, but only on the form

Additional fixes for Power Level box

---

mff_rams_plugin/models.py

Imported dealers would be counted as having tables, but it wouldn't show up on the form. This fixes that.

Fix dealer tables data type

---

mff_rams_plugin/models.py

Everyone's always imported as an attendee, but we need to preserve staff's badge number for matching. This gives the imported staff a staff ribbon so the system will let you save the attendee.

Ensure imported staff have a staff ribbon

---

mff_rams_plugin/__init__.py
mff_rams_plugin/receipt_items.py
mff_rams_plugin/templates/emails/dealers/application.html
mff_rams_plugin/templates/emails/dealers/approved.html

Fixes a bug where this plugin's receipt items weren't being included. Also fixes the emails for dealers and removes 'at the con' text from the approval email. Depends on https://github.com/MidwestFurryFandom/rams/pull/577.

Update dealer emails and costs

---

mff_rams_plugin/templates/landing/index.html

Was hard-coded for ??? reasons. Now not, since we need this again for 2022.

Swapped covid policy link text to name & year

---

mff_rams_plugin/config.py
mff_rams_plugin/model_checks.py
mff_rams_plugin/models.py

Apparently I hardcoded the "Child Badge" type at some point. This removes it for MFF. Also includes a very minor fix for undo_extras.

Stop requiring under-12 badge

---

mff_rams_plugin/model_checks.py
mff_rams_plugin/models.py
mff_rams_plugin/receipt_items.py
mff_rams_plugin/templates/emails/dealers/application.html
mff_rams_plugin/templates/emails/dealers/approved.html
mff_rams_plugin/templates/groupextra.html

Fixes the MFF version of the dealer approval email to use the recently-added default_ cost property. Also removes a collision between a named custom property and the default_ cost property.

Update MFF dealer emails with default costs

---

mff_rams_plugin/config.py

This override doesn't really work when you have price bumps, so we're going to actually set it in config instead.

Remove DEALER_BADGE_PRICE override

---

mff_rams_plugin/receipt_items.py
mff_rams_plugin/templates/groupextra.html

Turns out we don't want the power fee added on top of the custom cost, which makes sense now that I realize the custom power fee does not require auto_recalc to be turned off

Don't add power to custom cost

---

mff_rams_plugin/templates/emails/reg_workflow/under_18_reminder.txt

Actually use the configured consent form URL

---

mff_rams_plugin/models.py

We were using the config-based discount (currently set to $35) if it was more than the custom discount, but this was making one-day badges free. Not ideal.

Stop using config discounts for children

---

mff_rams_plugin/receipt_items.py

I just found this while adding cost_changes to MAGFest -- the server was throwing an error about the cost_changes property not existing. I have no idea if this ever worked for MFF, but if it didn't, it apparently would have failed silently.

Fix cost_changes additions

---

mff_rams_plugin/models.py

Enables https://github.com/MidwestFurryFandom/rams/pull/694 for dealers.

Enable adding existing badges for dealers

---

mff_rams_plugin/forms.py

The dealer form was requiring a power selection even if the field was locked. This is an old bug that was hidden by the fact that we weren't actually running validations on existing groups.

Fix power level validations

---

mff_rams_plugin/config.py
mff_rams_plugin/configspec.ini
mff_rams_plugin/forms.py
mff_rams_plugin/models.py
mff_rams_plugin/templates/forms/attendee/badge_extras.html

Adds the ability to select either a one-day badge or a weekend badge, which swaps between two sets of badge options. Attendees can upgrade from any one-day badge to any weekend badge, and the one-day/weekend option is hidden if the attendee already has a weekend badge.
Also fixes a bug introduced when adding the group name check for attendees by making the group name field on the third page optional for non-dealers.

Presell one-day badges during prereg

---

mff_rams_plugin/models.py
mff_rams_plugin/templates/hotel_lottery/lottery_tos.html

Removes a duplicate header and reflects a change in the main repo where we moved the staff lottery check to the Attendee class.

Updates for hotel lottery changes

---

mff_rams_plugin/forms.py
mff_rams_plugin/templates/forms/attendee/badge_extras.html

Adds a callout to select which day you want, and a validation for if you don't do it. Requested in the last status update meeting.

Add validation for single-day badges

---

mff_rams_plugin/configspec.ini
mff_rams_plugin/models.py

Should fix the issue where dealers were un-uploading their table photos.

Stop clearing table photo filename on null upload

---

mff_rams_plugin/models.py
mff_rams_plugin/templates/emails/dealers/approved.html
mff_rams_plugin/templates/forms/hotel/room_lottery.html

If we have to hold off on launching SignNow docs, it doesn't make sense to ask for money two weeks after approval as the dealer might not even be able to pay.
Also updates the approval email to account for this case.

Make dealer_payment_due check SignNow doc

---

mff_rams_plugin/templates/emails/dealers/approved.html
mff_rams_plugin/templates/emails/dealers/declined.txt
mff_rams_plugin/templates/emails/dealers/payment_confirmation.html
mff_rams_plugin/templates/emails/dealers/payment_reminder.txt
mff_rams_plugin/templates/emails/dealers/pending_waitlisted.txt
mff_rams_plugin/templates/emails/dealers/waitlist_closing.txt
mff_rams_plugin/templates/emails/placeholders/dealer.txt
mff_rams_plugin/templates/emails/placeholders/guest.txt
mff_rams_plugin/templates/emails/placeholders/imported_volunteer.txt
mff_rams_plugin/templates/emails/placeholders/panelist.txt
mff_rams_plugin/templates/emails/placeholders/regular.txt
mff_rams_plugin/templates/emails/placeholders/reminder.txt
mff_rams_plugin/templates/emails/placeholders/volunteer.txt
mff_rams_plugin/templates/emails/reg_workflow/group_confirmation.html
mff_rams_plugin/templates/emails/reg_workflow/under_18_reminder.txt

This might be the problem with our emails not updating -- even if not, we should still fix this so that the email signatures aren't blank.

Fix email signatures for custom emails
